apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ipFamilyPolicy: {{ .ipFamilyPolicy }}
  ipFamilies:
    {{- toYaml .ipFamilies | nindent 4 }}
  ports:
    {{- range $name, $port := .ports }}
    - port: {{ $port }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  {{- end }}{{/* end-with .service */}}
  selector:
    {{- include "stalwart-mail.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main
